
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_1_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_1_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_1_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_1_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_1_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_1_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_1_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_1_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_1_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_1_3 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_1/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_1_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_1_3 2>&1

# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_2_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_2_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_2_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_2_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_2_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_2_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_2_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_2_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_2_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_2_3 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_2/rob0_spam_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_2_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_2_3 2>&1

# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_3_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_3_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_1/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_3_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_3_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_3_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_3_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_3_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_3_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_single_img_3_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_single_img_3_3 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/spam_5_2_val4_noflip_3/rob0_spam_single_side_env_nobg_sam_iteration_27 -dp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/spam_5_2_val4_noflip_3/inerf_data_iter_28 -out /home/saptarshi/dev/CustomComposer/inerf_res/spam_multi_img_3_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/spam_multi_img_3_3 2>&1

# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_1/rob0_small_mug_single_side_env_nobg_sam_iteration_22 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_1_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_1_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_1/rob0_small_mug_single_side_env_nobg_sam_iteration_22 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_1_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_1_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_1/rob0_small_mug_single_side_env_nobg_sam_iteration_22 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_1_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_1_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_1/rob0_small_mug_single_side_env_nobg_sam_iteration_22 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_1_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_1_2 2>&1

# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_2/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_2_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_2_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_2/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_2_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_2_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_2/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_2_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_2_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_2/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_2_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_2_2 2>&1

# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_3/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_3_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_3_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_3/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_1/inerf_data_iter_23 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_3_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_3_1 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_3/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_single_img_3_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_single_img_3_2 2>&1
# CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/small_mug_5_2_val4_noflip_3/rob0_small_mug_single_side_env_nobg_sam_iteration_21 -dp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/small_mug_5_2_val4_noflip_2/inerf_data_iter_22 -out /home/saptarshi/dev/CustomComposer/inerf_res/small_mug_multi_img_3_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/small_mug_multi_img_3_2 2>&1

CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_1_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_1_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_1_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_1_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_1_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_1_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_1_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_1_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_1_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_1_3 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_1/rob0_cheezit_single_side_env_nobg_sam_iteration_23 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_1_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_1_3 2>&1

CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_2_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_2_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_2_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_2_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_2_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_2_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_2_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_2_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_2_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_2_3 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_2/rob0_cheezit_single_side_env_nobg_sam_iteration_29 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_2_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_2_3 2>&1

CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_3_1 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_3_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_1/inerf_data_iter_24 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_3_1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_3_1 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_3_2 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_3_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/inerf_data_iter_30 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_3_2 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_3_2 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_single_img_3_3 --num-images 1 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_single_img_3_3 2>&1
CUDA_AVAILABLE_DEVICES=1 python3 inerf_results_multi_image.py -mn workdir/cheezit_5_2_val4_noflip_flip_21_new_3/rob0_cheezit_single_side_env_nobg_sam_iteration_24 -dp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_2/merged_images_0 -inp /home/saptarshi/dev/CustomComposer/workdir/cheezit_5_2_val4_noflip_flip_21_new_3/inerf_data_iter_25 -out /home/saptarshi/dev/CustomComposer/inerf_res/cheezit_multi_img_3_3 >/home/saptarshi/dev/CustomComposer/inerf_res/outs/cheezit_multi_img_3_3 2>&1
